sudo: required

services:
  - docker

env:
  global:
    - VERSION=latest
    - DOCKER_LOGIN=crazymax
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=7zip
    - QUAY_LOGIN=crazymax
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=7zip
    - secure: dJG0Ltmy958/l8bVaCezUYN4P8opIL6SkF4oNnUMm5razOr5KTe9wqbFzbH3Lf4vlQfec89+tiQeKqhemVdG+lPotH5Tlx4Pv35QyhwkIXoVrqWwnsB7Pg9QOKZmPgVG/9mz1xrPxjH8t9YIaNoy8cia1tBs6Z4V21wnLJfIrbSNwfpSxys7ub4/lHJhMkTj7k+zVo5BziqAdUnEUqT/Gz2HqMvZusyPuGmG9mtxsYMWfa8f7TXRBsua0OMDkcacrPz4Ha50nEuY912BQnrIocoihQWG2U5Vcc+J9pxAQkCQM61bj9dEiRxN20Qj7p4PqphM1Hkw2NfRgXKHZK7SOm7NtzY3U4SyqZhDuZ5s9g94Pl2MBBdnA2gWhwxGZILcSersjPOJYe177STgM1T4SJXUSX4J2yaW3wQlwYenkncnln3tTZfR5eEKCKQ7AUJFK//tTKnaKOjs/PsbpCT9n5loZ0P3M7JJc3vVPnUX/F+GDnri+nsnxAv3E0LP4hNxe14cq/NcSUYpd0cUjlJI78SH2jmbqdAAoYWwq5nxzKvy1UncUVaZc5qhSlwRpnXgf1lcNYzGgRbyoLcGfXFn7IM3+n7lX6OXQ0zi+doxXlxVpZrFnidyfh6hzcHw9M77rYPoxjOT6Et06VeUKBlydqJHCNbyurykSFu4C8gKBmE= # DOCKER_PASSWORD
    - secure: vULMPO0Zmdus4p44OuBWHR0ufenn7+O3rxabun7IOHhditbcXZJ3pIKIpZrFEq6ruN8EPUDceFD7ggagdFLlz8czrKPzWv5BcniB/5qCuPzNCdzEMukBFL0WXknEGOspt17G9P1fIPE/3cO6wf05C+5mMNyWoLcFGWW3Jw2d0BDJYJd5ncVfnSi0eza4qKb791nAULDEm0iLvfFoEoKjcx12Jo9A3aS8bJAYlBf9wtlEmcZti0eTw6N68bCnryf9XQqKUzrg3dZJi0BCm2v9j+l9P4b6kNKEJsoyncOkgIbE0QPWwy5Ij8xNtJDqb4e3d2GXRUGuNf3oqZsh2wU7nQmC6cn0fDQ4FO99ycmDKhB2zMPsbYrCR5xv3zxtS5FGm7hU+Gj8fDqbhJF0QNLlp2y72aTmyT6Gh2wC2rBOC1KWrf4wc/lMEMEQZUDM3/0Kk9p/c8L1mo+1yNCOxk3/P+cWjttdRSbX/vf8psIWj5z/8nfZU6neAWp8wPLWUprrRAghA5I8Lzh7/HsY7Oiv1VZCa8ZwZBWD6FQwRh+hduql19ZmDFGJXfQuYJxXVVafm6WdsvPb9IyQSlA9IqQqlLj0Ab0qQTQ9Auc8H+zI+XrfWgkaDjfRSZBFzJIABE0ZbmWiq2gNV3EHOkB1EikuiNJNmP42D/ATHJbabeFkbZw= # QUAY_PASSWORD

before_install:
  - sudo apt-get update
  - docker --version

script: ./build.sh

notifications:
  email:
    recipients:
      - travisci@crazymax.dev
    on_success: always
    on_failure: always
